//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mega.Common.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("43")]
        public int CFG_SYSTEM_ADMIN_ROLE_UDCITEM_KEY {
            get {
                return ((int)(this["CFG_SYSTEM_ADMIN_ROLE_UDCITEM_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CFG_USER_PSW_VALID_DAYS_UDCITEM_KEY {
            get {
                return ((int)(this["CFG_USER_PSW_VALID_DAYS_UDCITEM_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ROL")]
        public string ROLES_UDC_KEY {
            get {
                return ((string)(this["ROLES_UDC_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CN")]
        public string COUNTRIES_UDC_KEY {
            get {
                return ((string)(this["COUNTRIES_UDC_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POP")]
        public string POPULATION_UDC_KEY {
            get {
                return ((string)(this["POPULATION_UDC_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("STATE")]
        public string STATE_UDC_KEY {
            get {
                return ((string)(this["STATE_UDC_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DIMTYP")]
        public string DIMTYPE_UDC_KEY {
            get {
                return ((string)(this["DIMTYPE_UDC_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MARSTA")]
        public string MARITAL_STATUS_UDC_KEY {
            get {
                return ((string)(this["MARITAL_STATUS_UDC_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int CFG_NULL_ROW_VALUE_UDCITEM_KEY {
            get {
                return ((int)(this["CFG_NULL_ROW_VALUE_UDCITEM_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CURR")]
        public string CURRENCY_UDC_KEY {
            get {
                return ((string)(this["CURRENCY_UDC_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SEX")]
        public string SEX_UDC_KEY {
            get {
                return ((string)(this["SEX_UDC_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TOPINV")]
        public string OPERATION_TYPE_UDC_KEY {
            get {
                return ((string)(this["OPERATION_TYPE_UDC_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("key that is already in use")]
        public string ExceptionMsgDuplicateKeyOnInsert {
            get {
                return ((string)(this["ExceptionMsgDuplicateKeyOnInsert"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("duplicate key")]
        public string ExceptionMsgDuplicateKeyOnInsert2 {
            get {
                return ((string)(this["ExceptionMsgDuplicateKeyOnInsert2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("STATOP")]
        public string OPERATION_STATUS_UDC_KEY {
            get {
                return ((string)(this["OPERATION_STATUS_UDC_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IVATYP")]
        public string IVATYPE_UDC_KEY {
            get {
                return ((string)(this["IVATYPE_UDC_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int CFG_BARCODE_MAX_SIZE_UDCITEM_KEY {
            get {
                return ((int)(this["CFG_BARCODE_MAX_SIZE_UDCITEM_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CURCHG")]
        public string CURRENCY_CHANGE_RATE_UDC_KEY {
            get {
                return ((string)(this["CURRENCY_CHANGE_RATE_UDC_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PAYTYP")]
        public string MOV_PAY_TYPE_UDC_KEY {
            get {
                return ((string)(this["MOV_PAY_TYPE_UDC_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BANK")]
        public string BANK_UDC_KEY {
            get {
                return ((string)(this["BANK_UDC_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int CFG_DIM_MAX_SIZE_UDCITEM_KEY {
            get {
                return ((int)(this["CFG_DIM_MAX_SIZE_UDCITEM_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int CFG_INVOICE_NAME_IN_TICKET_UDCITEM_KEY {
            get {
                return ((int)(this["CFG_INVOICE_NAME_IN_TICKET_UDCITEM_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IVAGRP")]
        public string IVAGROUP_UDC_KEY {
            get {
                return ((string)(this["IVAGROUP_UDC_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IVAVAL")]
        public string IVAVALUE_UDC_KEY {
            get {
                return ((string)(this["IVAVALUE_UDC_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int WEB_SYNCH_KEY {
            get {
                return ((int)(this["WEB_SYNCH_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=VM90_DESARROLLO;Initial Catalog=MegaAdmin;User ID=sa;Password=m3g4")]
        public string MegaAdminConnectionString {
            get {
                return ((string)(this["MegaAdminConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TOPINV")]
        public string INVENTORY_OP_TYPE_UDC_KEY {
            get {
                return ((string)(this["INVENTORY_OP_TYPE_UDC_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SUBTYP")]
        public string OPERATION_SUBTYPE_UDC_KEY {
            get {
                return ((string)(this["OPERATION_SUBTYPE_UDC_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DIFFUS")]
        public string DIFFUSION_MEDIA_UDC_KEY {
            get {
                return ((string)(this["DIFFUSION_MEDIA_UDC_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public int MAX_DAYS_RETURN_CONSIGNATION_UDC_KEY {
            get {
                return ((int)(this["MAX_DAYS_RETURN_CONSIGNATION_UDC_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int DATA_GRIDVIEW_PAGE_SIZE {
            get {
                return ((int)(this["DATA_GRIDVIEW_PAGE_SIZE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=VM90_DESARROLLO;Initial Catalog=MegaAdmin;User ID=sa;Password=m3g4")]
        public string _7201ConnectionString {
            get {
                return ((string)(this["_7201ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INPEN")]
        public string INVOICE_STATUS_PENDIENTE_XSA_UDCITEM_CODE {
            get {
                return ((string)(this["INVOICE_STATUS_PENDIENTE_XSA_UDCITEM_CODE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INFAC")]
        public string INVOICE_STATUS_FACTURADO_XSA_UDCITEM_CODE {
            get {
                return ((string)(this["INVOICE_STATUS_FACTURADO_XSA_UDCITEM_CODE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INGEN")]
        public string INVOICE_TYPE_GENERAL_UDCITEM_CODE {
            get {
                return ((string)(this["INVOICE_TYPE_GENERAL_UDCITEM_CODE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ININD")]
        public string INVOICE_TYPE_INDIVIDUAL_UDCITEM_CODE {
            get {
                return ((string)(this["INVOICE_TYPE_INDIVIDUAL_UDCITEM_CODE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RFCCOM")]
        public string RFC_Company {
            get {
                return ((string)(this["RFC_Company"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COMPF")]
        public string TIPO_COMPROBANTE_FISCAL {
            get {
                return ((string)(this["TIPO_COMPROBANTE_FISCAL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KEYXSA")]
        public string TOKEN_XSA_CODE {
            get {
                return ((string)(this["TOKEN_XSA_CODE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SERIE")]
        public string ID_SERIE_INVOICE {
            get {
                return ((string)(this["ID_SERIE_INVOICE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=VM90_DESARROLLO;Initial Catalog=MegaAdmin;User ID=sa")]
        public string MegaAdminConnectionString1 {
            get {
                return ((string)(this["MegaAdminConnectionString1"]));
            }
        }
    }
}
