//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18444.
// 
#pragma warning disable 1591

namespace Mega.POS.XSAMegahealthService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FileReceiverServiceHttpBinding", Namespace="http://xsafilereceiver.webservices.manager.xsa.tralix.com")]
    public partial class FileReceiverService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback obtenerEstadoDocumentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback guardarDocumentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback guardarDocumentoB2BOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FileReceiverService() {
            this.Url = global::Mega.POS.Properties.Settings.Default.Mega_POS_XSAService_FileReceiverService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event obtenerEstadoDocumentoCompletedEventHandler obtenerEstadoDocumentoCompleted;
        
        /// <remarks/>
        public event guardarDocumentoCompletedEventHandler guardarDocumentoCompleted;
        
        /// <remarks/>
        public event guardarDocumentoB2BCompletedEventHandler guardarDocumentoB2BCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://xsafilereceiver.webservices.manager.xsa.tralix.com", ResponseNamespace="http://xsafilereceiver.webservices.manager.xsa.tralix.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string obtenerEstadoDocumento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2) {
            object[] results = this.Invoke("obtenerEstadoDocumento", new object[] {
                        in0,
                        in1,
                        in2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerEstadoDocumentoAsync(string in0, string in1, string in2) {
            this.obtenerEstadoDocumentoAsync(in0, in1, in2, null);
        }
        
        /// <remarks/>
        public void obtenerEstadoDocumentoAsync(string in0, string in1, string in2, object userState) {
            if ((this.obtenerEstadoDocumentoOperationCompleted == null)) {
                this.obtenerEstadoDocumentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerEstadoDocumentoOperationCompleted);
            }
            this.InvokeAsync("obtenerEstadoDocumento", new object[] {
                        in0,
                        in1,
                        in2}, this.obtenerEstadoDocumentoOperationCompleted, userState);
        }
        
        private void OnobtenerEstadoDocumentoOperationCompleted(object arg) {
            if ((this.obtenerEstadoDocumentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerEstadoDocumentoCompleted(this, new obtenerEstadoDocumentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://xsafilereceiver.webservices.manager.xsa.tralix.com", ResponseNamespace="http://xsafilereceiver.webservices.manager.xsa.tralix.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void guardarDocumento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in4) {
            this.Invoke("guardarDocumento", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4});
        }
        
        /// <remarks/>
        public void guardarDocumentoAsync(string in0, string in1, string in2, string in3, string in4) {
            this.guardarDocumentoAsync(in0, in1, in2, in3, in4, null);
        }
        
        /// <remarks/>
        public void guardarDocumentoAsync(string in0, string in1, string in2, string in3, string in4, object userState) {
            if ((this.guardarDocumentoOperationCompleted == null)) {
                this.guardarDocumentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnguardarDocumentoOperationCompleted);
            }
            this.InvokeAsync("guardarDocumento", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4}, this.guardarDocumentoOperationCompleted, userState);
        }
        
        private void OnguardarDocumentoOperationCompleted(object arg) {
            if ((this.guardarDocumentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.guardarDocumentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://xsafilereceiver.webservices.manager.xsa.tralix.com", ResponseNamespace="http://xsafilereceiver.webservices.manager.xsa.tralix.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void guardarDocumentoB2B([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2) {
            this.Invoke("guardarDocumentoB2B", new object[] {
                        in0,
                        in1,
                        in2});
        }
        
        /// <remarks/>
        public void guardarDocumentoB2BAsync(string in0, string in1, string in2) {
            this.guardarDocumentoB2BAsync(in0, in1, in2, null);
        }
        
        /// <remarks/>
        public void guardarDocumentoB2BAsync(string in0, string in1, string in2, object userState) {
            if ((this.guardarDocumentoB2BOperationCompleted == null)) {
                this.guardarDocumentoB2BOperationCompleted = new System.Threading.SendOrPostCallback(this.OnguardarDocumentoB2BOperationCompleted);
            }
            this.InvokeAsync("guardarDocumentoB2B", new object[] {
                        in0,
                        in1,
                        in2}, this.guardarDocumentoB2BOperationCompleted, userState);
        }
        
        private void OnguardarDocumentoB2BOperationCompleted(object arg) {
            if ((this.guardarDocumentoB2BCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.guardarDocumentoB2BCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void obtenerEstadoDocumentoCompletedEventHandler(object sender, obtenerEstadoDocumentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerEstadoDocumentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerEstadoDocumentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void guardarDocumentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void guardarDocumentoB2BCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591